## Write a NumPy program to test whether none of the elements of a given array is zero.

In [1]:
import numpy as np
a=([[1,2],[1,3]])
result=np.all(a)
if result=="True":
    print("array does not have any zeros")
else:
    pass

## Write a NumPy program to create an array of 5 zeros, 5 ones, 5 fives.

In [13]:
a= np.ones((5),dtype=int)
print(0*a)
print(a)
print(5*a)


[0 0 0 0 0]
[1 1 1 1 1]
[5 5 5 5 5]
